### ISSUE TITLE
Server Down?

### ISSUE THREAD

**Issue by kingofthedepths** [slashinfty/bracketeer#1]
**If possible, please upload the json of your tournament!**
You can use !json to get a copy if the tournament is active.

**Describe the bug**
I believe the server is currently down, my commands are getting an "application did not respond" message

**To Reproduce**
type in any command in the Discord.

**Expected behavior**

**Screenshots**

**Date & Time**
When the bug occurred, so logs can be checked.
15 Apr 2022

Bot is new to the server, I am a tournament organizer but not the server admin.

**Comment by slashinfty** [comment]
Bot crashed, but has been restarted. If you need to reach me about the bot crashing, you can message me on Discord (slashinfty#6805). I'm happy to join a server if you need more assistance.

**Comment by kingofthedepths** [comment]
Looks like it crashed again!
